*Note: You are currently reading this using Google Colaboratory which is a cloud-hosted version of Jupyter Notebook. This is a document containing both text cells for documentation and runnable code cells. If you are unfamiliar with Jupyter Notebook, watch this 3-minute introduction before starting this challenge: https://www.youtube.com/watch?v=inN8seMm7UI*

---

In this challenge, you will create a book recommendation algorithm using **K-Nearest Neighbors**.

You will use the [Book-Crossings dataset](http://www2.informatik.uni-freiburg.de/~cziegler/BX/). This dataset contains 1.1 million ratings (scale of 1-10) of 270,000 books by 90,000 users. 

After importing and cleaning the data, use `NearestNeighbors` from `sklearn.neighbors` to develop a model that shows books that are similar to a given book. The Nearest Neighbors algorithm measures distance to determine the “closeness” of instances.

Create a function named `get_recommends` that takes a book title (from the dataset) as an argument and returns a list of 5 similar books with their distances from the book argument.

This code:

`get_recommends("The Queen of the Damned (Vampire Chronicles (Paperback))")`

should return:

```
[
  'The Queen of the Damned (Vampire Chronicles (Paperback))',
  [
    ['Catch 22', 0.793983519077301], 
    ['The Witching Hour (Lives of the Mayfair Witches)', 0.7448656558990479], 
    ['Interview with the Vampire', 0.7345068454742432],
    ['The Tale of the Body Thief (Vampire Chronicles (Paperback))', 0.5376338362693787],
    ['The Vampire Lestat (Vampire Chronicles, Book II)', 0.5178412199020386]
  ]
]
```

Notice that the data returned from `get_recommends()` is a list. The first element in the list is the book title passed in to the function. The second element in the list is a list of five more lists. Each of the five lists contains a recommended book and the distance from the recommended book to the book passed in to the function.

If you graph the dataset (optional), you will notice that most books are not rated frequently. To ensure statistical significance, remove from the dataset users with less than 200 ratings and books with less than 100 ratings.

The first three cells import libraries you may need and the data to use. The final cell is for testing. Write all your code in between those cells.

In [316]:
# import libraries (you may add additional imports but you may not have to)
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors
import matplotlib.pyplot as plt
import zipfile

In [ ]:
# get data files
!wget https://cdn.freecodecamp.org/project-data/books/book-crossings.zip

file_name = "book-crossings.zip"
fileToExtract = zipfile.ZipFile(file_name, 'r')
fileToExtract.extractall()

books_filename = 'BX-Books.csv'
ratings_filename = 'BX-Book-Ratings.csv'

In [425]:
# import csv data into dataframes
df_books = pd.read_csv(
    books_filename,
    encoding = "ISO-8859-1",
    sep=";",
    header=0,
    names=['isbn', 'title', 'author'],
    usecols=['isbn', 'title', 'author'],
    dtype={'isbn': 'str', 'title': 'str', 'author': 'str'})

df_ratings = pd.read_csv(
    ratings_filename,
    encoding = "ISO-8859-1",
    sep=";",
    header=0,
    names=['user', 'isbn', 'rating'],
    usecols=['user', 'isbn', 'rating'],
    dtype={'user': 'int32', 'isbn': 'str', 'rating': 'float32'})

In [426]:
# add your code here - consider creating a new cell for each section of code
isbn_keep = df_ratings.groupby(['isbn'])['rating'].count()>=100
isbn_keep = isbn_keep[isbn_keep].index
print(isbn_keep)

users_keep = df_ratings.groupby(['user'])['rating'].count()>=200
users_keep = users_keep[users_keep].index
print(users_keep)

df_ratings = df_ratings.loc[df_ratings['user'].isin(users_keep)]
df_ratings = df_ratings.loc[df_ratings['isbn'].isin(isbn_keep)]

df_books.drop_duplicates(['title'],keep = 'first')

books_with_ratings = pd.merge(df_ratings, df_books, on='isbn')



Index(['002542730X', '0060008032', '0060096195', '006016848X', '0060173289',
       '0060175400', '006019491X', '0060199652', '0060391626', '0060392452',
       ...
       '1558744630', '1558745157', '1559029838', '1573225517', '1573225789',
       '1573227331', '1573229326', '1573229571', '1592400876', '1878424319'],
      dtype='object', name='isbn', length=731)
Int64Index([   254,   2276,   2766,   2977,   3363,   3757,   4017,   4385,
              6242,   6251,
            ...
            274004, 274061, 274301, 274308, 274808, 275970, 277427, 277478,
            277639, 278418],
           dtype='int64', name='user', length=905)


In [427]:
df_books

isbn                                              title  \
0       0195153448                                Classical Mythology   
1       0002005018                                       Clara Callan   
2       0060973129                               Decision in Normandy   
3       0374157065  Flu: The Story of the Great Influenza Pandemic...   
4       0393045218                             The Mummies of Urumchi   
...            ...                                                ...   
271374  0440400988                         There's a Bat in Bunk Five   
271375  0525447644                            From One to One Hundred   
271376  006008667X  Lily Dale : The True Story of the Town that Ta...   
271377  0192126040                        Republic (World's Classics)   
271378  0767409752  A Guided Tour of Rene Descartes' Meditations o...   

                      author  
0         Mark P. O. Morford  
1       Richard Bruce Wright  
2               Carlo D'Este  
3           Gina Bari Kolata  
4            E. J. W. Barber  
...                      ...  
271374        Paula Danziger  
271375            Teri Sloat  
271376      Christine Wicker  
271377                 Plato  
271378   Christopher  Biffle  

[271379 rows x 3 columns]

In [428]:
df_ratings

user        isbn  rating
1456     277427  002542730X    10.0
1469     277427  0060930535     0.0
1471     277427  0060934417     0.0
1474     277427  0061009059     9.0
1484     277427  0140067477     0.0
...         ...         ...     ...
1147304  275970  0804111359     0.0
1147436  275970  140003065X     0.0
1147439  275970  1400031346     0.0
1147440  275970  1400031354     0.0
1147441  275970  1400031362     0.0

[49781 rows x 3 columns]

In [452]:
books_with_ratings2 = books_with_ratings.drop_duplicates(['title', 'user'])
books_with_ratings2.drop_duplicates(['title', 'user'])

user        isbn  rating  \
0      277427  002542730X    10.0   
1        3363  002542730X     0.0   
2       11676  002542730X     6.0   
3       12538  002542730X    10.0   
4       13552  002542730X     0.0   
...       ...         ...     ...   
49512  238864  0399149325     0.0   
49513  251843  0399149325     1.0   
49514  253821  0399149325     0.0   
49515  265115  0399149325     0.0   
49516  266226  0399149325     0.0   

                                                   title             author  
0      Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
1      Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
2      Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
3      Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
4      Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
...                                                  ...                ...  
49512  Portrait of a Killer: Jack the Ripper -- Case ...  Patricia Cornwell  
49513  Portrait of a Killer: Jack the Ripper -- Case ...  Patricia Cornwell  
49514  Portrait of a Killer: Jack the Ripper -- Case ...  Patricia Cornwell  
49515  Portrait of a Killer: Jack the Ripper -- Case ...  Patricia Cornwell  
49516  Portrait of a Killer: Jack the Ripper -- Case ...  Patricia Cornwell  

[49136 rows x 5 columns]

In [453]:
# Create k neighbors classifier
df_samples_pivot = pd.pivot_table(data=books_with_ratings2, values='rating', index='title', columns='user').fillna(0)
df_matrix = csr_matrix(df_samples_pivot.values)

neigh = NearestNeighbors(algorithm='auto', leaf_size=30, metric='cosine',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)
neigh.fit(df_matrix)

NearestNeighbors(metric='cosine')

In [454]:
df_samples_pivot

user                                                254     2276    2766    \
title                                                                        
1984                                                   9.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0    10.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
A Beautiful Mind: The Life of Mathematical Geni...     0.0     0.0     0.0   
...                                                    ...     ...     ...   
Without Remorse                                        0.0     0.0     0.0   
Year of Wonders                                        0.0     0.0     0.0   
You Belong To Me                                       0.0     0.0     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0     0.0     0.0   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   

user                                                2977    3363    4017    \
title                                                                        
1984                                                   0.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0     0.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
A Beautiful Mind: The Life of Mathematical Geni...     0.0     0.0     0.0   
...                                                    ...     ...     ...   
Without Remorse                                        0.0     0.0     0.0   
Year of Wonders                                        7.0     0.0     0.0   
You Belong To Me                                       0.0     0.0     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0     0.0     0.0   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   

user                                                4385    6242    6251    \
title                                                                        
1984                                                   0.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0     0.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
A Beautiful Mind: The Life of Mathematical Geni...     0.0     0.0     0.0   
...                                                    ...     ...     ...   
Without Remorse                                        0.0     0.0     0.0   
Year of Wonders                                        0.0     7.0     0.0   
You Belong To Me                                       0.0     0.0     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0     0.0     0.0   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   

user                                                6323    ...  274004  \
title                                                       ...           
1984                                                   0.0  ...     0.0   
1st to Die: A Novel                                    0.0  ...     0.0   
2nd Chance                                             0.0  ...     0.0   
4 Blondes                                              0.0  ...     0.0   
A Beautiful Mind: The Life of Mathematical Geni...     0.0  ...     0.0   
...                                                    ...  ...     ...   
Without Remorse                                        0.0  ...     0.0   
Year of Wonders                                        0.0  ...     0.0   
You Belong To Me                                       0.0  ...     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0  ...     0.0   
\O\" Is for Outlaw"                                    

In [461]:
# function to return recommended books - this will be tested
def get_recommends(book = ""):

    X = df_samples_pivot[df_samples_pivot.index == book]
    X = X.to_numpy().reshape(1,-1)
    
    distances, indices = neigh.kneighbors(X,n_neighbors=6)

    print(indices)

    recommended_books = []
    for x in reversed(range(1,6)):
          bookrecommended = [df_samples_pivot.index[indices.flatten()[x]], distances.flatten()[x]]
          recommended_books.append(bookrecommended)
    recommended_books = [book, recommended_books]
    
    return recommended_books

In [462]:
get_recommends("Girl in Hyacinth Blue")

[[207  33  47 147  66 144]]


['Girl in Hyacinth Blue',
 [['Digital Fortress : A Thriller', 0.7617674],
  ['Balzac and the Little Chinese Seamstress : A Novel', 0.73700106],
  ['Divine Secrets of the Ya-Ya Sisterhood: A Novel', 0.7251636],
  ['Angels', 0.7128463],
  ['About a Boy (Movie Tie-In)', 0.7092408]]]

Use the cell below to test your function. The `test_book_recommendation()` function will inform you if you passed the challenge or need to keep trying.

In [463]:
books = get_recommends("Where the Heart Is (Oprah's Book Club (Paperback))")
print(books)

def test_book_recommendation():
  test_pass = True
  recommends = get_recommends("Where the Heart Is (Oprah's Book Club (Paperback))")
  if recommends[0] != "Where the Heart Is (Oprah's Book Club (Paperback))":
    test_pass = False
  recommended_books = ["I'll Be Seeing You", 'The Weight of Water', 'The Surgeon', 'I Know This Much Is True']
  recommended_books_dist = [0.8, 0.77, 0.77, 0.77]
  for i in range(2): 
    if recommends[1][i][0] not in recommended_books:
      test_pass = False
    if abs(recommends[1][i][1] - recommended_books_dist[i]) >= 0.05:
      test_pass = False
  if test_pass:
    print("You passed the challenge! 🎉🎉🎉🎉🎉")
  else:
    print("You haven't passed yet. Keep trying!")

test_book_recommendation()

[[654 539 240 597 614 243]]
["Where the Heart Is (Oprah's Book Club (Paperback))", [["I'll Be Seeing You", 0.8016211], ['The Weight of Water', 0.77085835], ['The Surgeon', 0.7699411], ['I Know This Much Is True', 0.7677075], ['The Lovely Bones: A Novel', 0.7234864]]]
[[654 539 240 597 614 243]]
You passed the challenge! 🎉🎉🎉🎉🎉
